import { reactive } from 'vue'

export const store = reactive({
  feeTypeList: [
    { code: 1, name: 'Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 2, name: 'Reissue Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 3, name: 'Cancellation Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 4, name: 'Refund Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 5, name: 'MDR Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 6, name: 'After Office Charge', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 7, name: 'Late Payment', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 8, name: 'Domestic Flight Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 9, name: 'International Flight Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 10, name: 'Domestic Hotel Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 11, name: 'Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 12, name: 'Reissue Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 13, name: 'Cancellation Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 14, name: 'Refund Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 15, name: 'MDR Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 16, name: 'After Office Charge', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 17, name: 'Late Payment', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 18, name: 'Domestic Flight Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 19, name: 'International Flight Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 20, name: 'Domestic Hotel Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 21, name: 'Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 22, name: 'Reissue Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 23, name: 'Cancellation Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 24, name: 'Refund Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 25, name: 'MDR Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 26, name: 'After Office Charge', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 27, name: 'Late Payment', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 28, name: 'Domestic Flight Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 29, name: 'International Flight Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 30, name: 'Domestic Hotel Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 31, name: 'Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 32, name: 'Reissue Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 33, name: 'Cancellation Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 34, name: 'Refund Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 35, name: 'MDR Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 36, name: 'After Office Charge', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 37, name: 'Late Payment', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 38, name: 'Domestic Flight Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 39, name: 'International Flight Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 40, name: 'Domestic Hotel Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 41, name: 'Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 42, name: 'Reissue Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 43, name: 'Cancellation Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 44, name: 'Refund Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 45, name: 'MDR Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 46, name: 'After Office Charge', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 47, name: 'Late Payment', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 48, name: 'Domestic Flight Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 49, name: 'International Flight Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 50, name: 'Domestic Hotel Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 51, name: 'Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 52, name: 'Reissue Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 53, name: 'Cancellation Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 54, name: 'Refund Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 55, name: 'MDR Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 56, name: 'After Office Charge', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 57, name: 'Late Payment', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 58, name: 'Domestic Flight Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 59, name: 'International Flight Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 60, name: 'Domestic Hotel Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 61, name: 'Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 62, name: 'Reissue Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 63, name: 'Cancellation Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 64, name: 'Refund Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 65, name: 'MDR Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 66, name: 'After Office Charge', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 67, name: 'Late Payment', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 68, name: 'Domestic Flight Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 69, name: 'International Flight Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 70, name: 'Domestic Hotel Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 71, name: 'Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 72, name: 'Reissue Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 73, name: 'Cancellation Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 74, name: 'Refund Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 75, name: 'MDR Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 76, name: 'After Office Charge', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 77, name: 'Late Payment', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 78, name: 'Domestic Flight Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 79, name: 'International Flight Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 80, name: 'Domestic Hotel Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 81, name: 'Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 82, name: 'Reissue Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 83, name: 'Cancellation Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 84, name: 'Refund Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 85, name: 'MDR Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 86, name: 'After Office Charge', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 87, name: 'Late Payment', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 88, name: 'Domestic Flight Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 89, name: 'International Flight Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 90, name: 'Domestic Hotel Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 91, name: 'Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 92, name: 'Reissue Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 93, name: 'Cancellation Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 94, name: 'Refund Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 95, name: 'MDR Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 96, name: 'After Office Charge', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 97, name: 'Late Payment', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 98, name: 'Domestic Flight Service Fee', status: 'Active', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 99, name: 'International Flight Service Fee', status: 'Inactive', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
    { code: 100, name: 'Domestic Hotel Service Fee', status: 'Inactive', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin turpis vel enim efficitur interdum.' },
  ],
  updateMultipleItem(selectedItem,status) {
    this.feeTypeList = this.feeTypeList.map(item => {
        let found = selectedItem.find(({code}) => code === item.code)
        item.status = found ? status : item.status

        return item
    })
  },
  deleteMultipleItem(selectedItem) {
    this.feeTypeList = this.feeTypeList.filter(item => !selectedItem.some(selItem => selItem.code === item.code))
  },
  deleteItem(index) {
    this.feeTypeList.splice(index,1)
  },
})